services:
  - type: web
    name: open-webui-api
    env: python              # ← change here
    branch: main
    region: virginia
    plan: starter

    buildCommand: |
      cd backend
      pip install --upgrade pip
      pip install -r requirements.txt

    startCommand: |
      uvicorn open_webui.main:app \
        --app-dir backend \
        --host 0.0.0.0 \
        --port $PORT \
        --forwarded-allow-ips='*'